### ISSUE TITLE
How to debug a crash with "Unhandled CPU exception"

### ISSUE THREAD

**Issue by kiler129** [pagabuc/kallsyms-extractor#1]
I have a 512MB memory dump from a QEMU machine. Attempting to extract symbols leads to the following error:

```
# python3 kallsyms.py ../../compromised_memory.bin
[+] Candidate kallsyms_on_each_symbol string found @ 0x177a63e
Done 4.28%
[+] Found a potential ksymtab with: 12278 elements
Done 4.47%
[+] Found a potential ksymtab with: 6201 elements
[+] Candidate kallsyms_on_each_symbol function va: 0xffffffff8108cce0 pa: 0x108cce0 name: 0xffffffff8177a63e
Traceback (most recent call last):
  File "kallsyms.py", line 114, in <module>
    for ksyms, va, pa in extract_kallsyms(dump):
  File "kallsyms.py", line 41, in extract_kallsyms
    ksyms = extract_symbols(dump, va, pa)
  File "/root/build/ram_anal/kallsyms-extractor-master/src/unicorn_magic.py", line 63, in extract_symbols
    mu.reg_write(UC_X86_REG_GS, 0x1000)
  File "/usr/local/lib/python3.4/dist-packages/unicorn/unicorn.py", line 447, in reg_write
    raise UcError(status)
unicorn.unicorn.UcError: Unhandled CPU exception (UC_ERR_EXCEPTION)
```

The OS I'm running kallsyms on is a Debian 8 (as I need an older gcc for other tasks) VM w/nested virtualization enabled:
```
# python3 --version
Python 3.4.2

# pip3 show unicorn
---
Name: unicorn
Version: 1.0.3
Location: /usr/local/lib/python3.4/dist-packages
Requires:

# lscpu | grep Virtual
Virtualization:        VT-x
Virtualization type:   full
```

Do you maybe have any idea how to debug this?

**Comment by pagabuc** [comment]
Hey @kiler129, sorry but I saw this issue only now. Can you please pull and try again? Thanks!
